export const UPDATE_FOO = 'UPDATE_FOO';
export const UPDATE_ZOOM_DATA = 'UPDATE_ZOOM_DATA';
export const UPDATE_DARK_MODE = 'UPDATE_DARK_MODE';
export const UPDATE_SCHEDULE_DATA = 'UPDATE_SCHEDULE_DATA';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const UPDATE_AUTO_JOIN = 'UPDATE_AUTO_JOIN';
